#ifndef GO_CONFIG_COMPILER_CLANG_HPP_INCLUDED
#define GO_CONFIG_COMPILER_CLANG_HPP_INCLUDED

//
//  clang.hpp
//
//  Copyright 2017-2019 Göran Orsander
//
//  This file is part of the GO.libraries.
//  Distributed under the GO Software License, Version 2.0.
//  See accompanying file LICENSE.md.
//

#if defined(__clang__)

#define GO_COMP_CLANG 1

#define GO_CLANG_VERSION (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)

// Compiler message
#define GO_MESSAGE(_message_) \
_Pragma message _message_

// C++ keyword typename support
#define GO_TYPENAME typename
#define GO_CPP_TYPENAME_REQUIRED 1

// C++ issue workarounds
#define GO_CHAR_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_WCHAR_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_CHAR16_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_CHAR32_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1

// C++11 support
#if (GO_CLANG_VERSION < 30800)
#define GO_NO_CXX11_MONEY_TIME_AND_HEXFLOAT_IO_MANIPULATORS 1
#endif  // #if (GO_CLANG_VERSION < 30800)
#if (GO_CLANG_VERSION < 30300)
#define GO_NO_CXX11_INHERITING_CONSTRUCTORS 1
#define GO_NO_CXX11_THREAD_LOCAL_STORAGE 1
#define GO_NO_CXX11_ATTRIBUTES 1
#endif  // #if (GO_CLANG_VERSION < 30300)
#if (GO_CLANG_VERSION < 30100)
#define GO_NO_CXX11_ATOMIC_OPERATIONS 1
#define GO_NO_CXX11_CONSTEXPR 1
#define GO_NO_CXX11_FORWARD_ENUM_DECLARATIONS 1
#define GO_NO_CXX11_INITIALIZER_LISTS 1
#define GO_NO_CXX11_LAMBDA_EXPRESSIONS 1
#define GO_NO_CXX11_USER_DEFINED_LITERALS 1
#endif  // #if (GO_CLANG_VERSION < 30100)
#if (GO_CLANG_VERSION < 30000)
#define GO_NO_CXX11_ALIGNAS 1
#define GO_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS 1
#define GO_NO_CXX11_DELEGATING_CONSTRUCTORS 1
#define GO_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS 1
#define GO_NO_CXX11_UNICODE_STRING_LITERALS 1
#define GO_NO_CXX11_TEMPLATE_ALIASES 1
#define GO_NO_CXX11_TYPE_ALIASES 1
#define GO_NO_CXX11_UNRESTRICTED_UNIONS 1
#define GO_NO_CXX11_TYPE_TRAITS 1
#define GO_NO_CXX11_RANGE_FOR_LOOP 1
#define GO_NO_CXX11_NON_STATIC_DATA_MEMBER_INITIALIZERS 1
#endif  // #if (GO_CLANG_VERSION < 30000)
#if (GO_CLANG_VERSION < 20900)
#define GO_NO_CXX11_ALIGNOF 1
#define GO_NO_CXX11_DECLTYPE 1
#define GO_NO_CXX11_EXTENDED_FRIEND_DECLARATIONS 1
#define GO_NO_CXX11_LOCAL_AND_UNNAMED_TYPES_AS_TEMPLATE_PARAMETERS 1
#define GO_NO_CXX11_INLINE_NAMESPACES 1
#define GO_NO_CXX11_NEW_CHARACTER_TYPES 1
#define GO_NO_CXX11_TRAILING_FUNCTION_RETURN_TYPES 1
#define GO_NO_CXX11_NULLPTR 1
#define GO_NO_CXX11_STATIC_ASSERT 1
#define GO_NO_CXX11_STRONGLY_TYPED_ENUM 1
#define GO_NO_CXX11_VARIADIC_TEMPLATES 1
#define GO_NO_CXX11_OVERRIDE_AND_FINAL 1
#define GO_NO_CXX11_REF_QUALIFIERS 1
#define GO_NO_CXX11_MAGIC_STATICS 1
#define GO_NO_CXX11_NOEXCEPT 1
#endif  // #if (GO_CLANG_VERSION < 20900)
#if (GO_CLANG_VERSION < 20800)
#define GO_NO_CXX11_AUTO 1
#define GO_NO_CXX11_EXTERN_TEMPLATE 1
#define GO_NO_CXX11_LONG_LONG 1
#define GO_NO_CXX11_RAW_STRING_LITERALS 1
#define GO_NO_CXX11_RIGHT_ANGLE_BRACKETS 1
#define GO_NO_CXX11_R_VALUE_REFERENCES 1
#define GO_NO_CXX11 1
#endif  // #if (GO_CLANG_VERSION < 20800)
#if defined(GO_CLANG_VERSION)
#define GO_NO_CXX11_DYNAMIC_POINTER_SAFETY 1
#endif  // #if defined(GO_CLANG_VERSION)
#define GO_NO_CXX11_LOCALTIME_S 1

#if defined(GO_NO_CXX11_CONSTEXPR)
#define GO_CONSTEXPR
#else
#define GO_CONSTEXPR constexpr
#endif  // #if defined(GO_NO_CXX11_CONSTEXPR)

#if defined(GO_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS)
#define GO_DEFAULT_CONSTRUCTOR {}
#define GO_DEFAULT_DESTRUCTOR {}
#else
#define GO_DEFAULT_CONSTRUCTOR = default;
#define GO_DEFAULT_DESTRUCTOR = default;
#endif  // #if defined(GO_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS)

#if defined(GO_NO_CXX11_NOEXCEPT)
#define GO_NOEXCEPT
#define GO_NOEXCEPT_OR_NOTHROW throw()
#define GO_NOEXCEPT_IF(_predicate_)
#define GO_NOEXCEPT_EXPR(_expression_) false
#else
#define GO_NOEXCEPT noexcept
#define GO_NOEXCEPT_OR_NOTHROW noexcept
#define GO_NOEXCEPT_IF(_predicate_) noexcept((_predicate_))
#define GO_NOEXCEPT_EXPR(_expression_) noexcept((_expression_))
#endif  // #if defined(GO_NO_CXX11_NOEXCEPT)

#if defined(GO_NO_CXX11_NULLPTR)
#define GONULLPTR NULL
#else
#define GO_NULLPTR nullptr
#endif  // #if defined(GO_NO_CXX11_NULLPTR)

#if defined(GO_NO_CXX11_OVERRIDE_AND_FINAL)
#define GO_FINAL
#define GO_OVERRIDE
#else
#define GO_FINAL final
#define GO_OVERRIDE override
#endif  // #if defined(GO_NO_CXX11_OVERRIDE_AND_FINAL)

#if defined(GO_NO_CXX11_TEMPLATE_ALIASES)
#define GO_USING(_alias_, _type_) typedef _type_ _alias_
#else
#define GO_USING(_alias_, _type_) using _alias_ = _type_;
#endif  // #if defined(GO_NO_CXX11_TEMPLATE_ALIASES)

// C++14 support
#if (GO_CLANG_VERSION < 30400)
#define GO_NO_CXX14_TWEAKED_WORDING_FOR_CONTEXTUAL_CONVERSIONS 1
#define GO_NO_CXX14_DECLTYPE_AUTO 1
#define GO_NO_CXX14_INITIALIZED_GENERALIZED_LAMBDA_CAPTURES 1
#define GO_NO_CXX14_GENERIC_POLYMORPHIC_LAMBDA_EXPRESSIONS 1
#define GO_NO_CXX14_VARIABLE_TEMPLATES 1
#define GO_NO_CXX14_EXTENDED_CONSTEXPR 1
#define GO_NO_CXX14_CLARIFYING_MEMORY_ALLOCATION 1
#define GO_NO_CXX14_DEPRECATED_ATTRIBUTE 1
#define GO_NO_CXX14_SIZED_DEALLOCATION 1
#define GO_NO_CXX14_SINGLE_QUOTE_AS_DIGIT_SEPARATOR 1
#define GO_NO_CXX14_CONSTEXPR_FOR_COMPLEX 1
#define GO_NO_CXX14_CONSTEXPR_FOR_CHRONO 1
#define GO_NO_CXX14_CONSTEXPR_FOR_ARRAY 1
#define GO_NO_CXX14_CONSTEXPR_FOR_INITIALIZER_LIST_UTILITY_AND_TUPLE 1
#define GO_NO_CXX14_IMPROVED_STD_INTEGRAL_CONSTANT 1
#define GO_NO_CXX14_USER_DEFINED_LITERALS_FOR_CHRONO_AND_STRING 1
#define GO_NO_CXX14_NULL_FORWARD_ITERATORS 1
#define GO_NO_CXX14_STD_QUOTED 1
#define GO_NO_CXX14_HETEROGENEOUS_ASSOCIATIVE_LOOKUP 1
#define GO_NO_CXX14_STD_INTEGER_SEQUENCE 1
#define GO_NO_CXX14_STD_SHARED_TIMED_MUTEX 1
#define GO_NO_CXX14_STD_EXCHANGE 1
#define GO_NO_CXX14_FIXING_CONSTEXPR_MEMBER_FUNCTIONS_WITHOUT_CONST 1
#define GO_NO_CXX14_STD_GET_T 1
#define GO_NO_CXX14_DUAL_RANGE_STD_EQUAL_STD_IS_PERMUTATION_STD_MISMATCH 1
#endif  // #if (GO_CLANG_VERSION < 30400)
#if (GO_CLANG_VERSION < 30300)
#define GO_NO_CXX14_MEMBER_INITIALIZERS_AND_AGGREGATES 1
#endif  // #if (GO_CLANG_VERSION < 30300)
#if (GO_CLANG_VERSION < 20900)
#define GO_NO_CXX14_BINARY_LITERALS 1
#endif  // #if (GO_CLANG_VERSION < 20900)
#if (GO_CLANG_VERSION < 20800)
#define GO_NO_CXX14_STD_RESULT_OF_AND_SFINAE 1
#define GO_NO_CXX14 1
#endif  // #if (GO_CLANG_VERSION < 20800)

// C++17 support
#if (GO_CLANG_VERSION < 80000)
#define GO_NO_CXX17_SPLICING_MAPS_AND_SETS 1
#endif  // #if (GO_CLANG_VERSION < 80000)
#if (GO_CLANG_VERSION < 70000)
#define GO_NO_CXX17_STD_FILESYSTEM 1
#define GO_NO_CXX17_STD_BYTE 1
#endif  // #if (GO_CLANG_VERSION < 70000)
#if (GO_CLANG_VERSION < 60000)
#define GO_NO_CXX17_REPLACEMENT_OF_CLASS_OBJECTS_CONTAINING_REFERENCE_MEMBERS 1
#endif  // #if (GO_CLANG_VERSION < 60000)
#if (GO_CLANG_VERSION < 50000)
#define GO_NO_CXX17_TEMPLATE_ARGUMENT_DEDUCTION_FOR_CLASS_TEMPLATES 1
#define GO_NO_CXX17_CONSTEXPR_LAMBDA_EXPRESSIONS 1
#endif  // #if (GO_CLANG_VERSION < 50000)
#if (GO_CLANG_VERSION < 40000)
#define GO_NO_CXX17_REMOVING_DEPRECATED_EXCEPTION_SPECIFICATIONS 1
#define GO_NO_CXX17_MAKE_EXCEPTION_SPECIFICATIONS_PART_OF_THE_TYPE_SYSTEM 1
#define GO_NO_CXX17_DYNAMIC_MEMORY_ALLOCATION_FOR_OVERALIGNED_DATA 1
#define GO_NO_CXX17_NONTYPE_TEMPLATE_PARAMETERS_WITH_AUTO_TYPE 1
#define GO_NO_CXX17_GUARANTEED_COPY_ELISION 1
#define GO_NO_CXX17_STRICTER_EXPRESSION_EVALUATION_ORDER 1
#define GO_NO_CXX17_PACK_EXPANSIONS_IN_USING_DECLARATIONS 1
#define GO_NO_CXX17_STRUCTURED_BINDINGS 1
#define GO_NO_CXX17_MATCHING_OF_TEMPLATE_TEMPLATE_ARGUMENTS_EXCLUDES_COMPATIBLE_TEMPLATES 1
#define GO_NO_CXX17_IMPROVING_STD_PAIR_AND_STD_TUPLE 1
#define GO_NO_CXX17_STD_ANY 1
#define GO_NO_CXX17_STD_VARIANT 1
#define GO_NO_CXX17_STD_OPTIONAL 1
#define GO_NO_CXX17_STD_STRING_VIEW 1
#endif  // #if (GO_CLANG_VERSION < 40000)
#if (GO_CLANG_VERSION < 30900)
#define GO_NO_CXX17_AGGREGATE_INITIALIZATION_OF_CLASSES_WITH_BASE_CLASSES 1
#define GO_NO_CXX17_LAMBDA_CAPTURE_OF_INDIRECTED_THIS 1
#define GO_NO_CXX17_USING_ATTRIBUTE_NAMESPACES_WITHOUT_REPETITION 1
#define GO_NO_CXX17_UNARY_FOLD_EXPRESSIONS_AND_EMPTY_PARAMETER_PACKS 1
#define GO_NO_CXX17_NEW_SPECIFICATION_FOR_INHERITING_CONSTRUCTORS 1
#define GO_NO_CXX17_DIRECT_LIST_INITIALIZATION_OF_ENUMERATIONS 1
#define GO_NO_CXX17_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR 1
#define GO_NO_CXX17_FALLTHROUGH_ATTRIBUTE 1
#define GO_NO_CXX17_NODISCARD_ATTRIBUTE 1
#define GO_NO_CXX17_MAYBE_UNUSED_ATTRIBUTE 1
#define GO_NO_CXX17_IGNORE_UNKNOWN_ATTRIBUTES 1
#define GO_NO_CXX17_CONSTEXPR_IF_STATEMENTS 1
#define GO_NO_CXX17_INIT_STATEMENTS_FOR_IF_AND_SWITCH 1
#define GO_NO_CXX17_INLINE_VARIABLES 1
#endif  // #if (GO_CLANG_VERSION < 30900)
#if (GO_CLANG_VERSION < 30800)
#define GO_NO_CXX17_NEW_AUTO_RULES_FOR_DIRECT_LIST_INITIALIZATION 1
#define GO_NO_CXX17_REMOVE_DEPRECATED_USE_OF_THE_REGISTER_KEYWORD 1
#define GO_NO_CXX17_REMOVE_DEPRECATED_OPERATOR_PLUSPLUS_BOOL 1
#endif  // #if (GO_CLANG_VERSION < 30800)
#if (GO_CLANG_VERSION < 30700)
#define GO_NO_CXX17_STD_UNCAUGHT_EXCEPTIONS 1
#define GO_NO_CXX17_STD_SHARED_MUTEX_UNTIMED 1
#endif  // #if (GO_CLANG_VERSION < 30700)
#if (GO_CLANG_VERSION < 30600)
#define GO_NO_CXX17_NESTED_NAMESPACE_DEFINITION 1
#define GO_NO_CXX17_ATTRIBUTES_FOR_NAMESPACES_AND_ENUMERATORS 1
#define GO_NO_CXX17_U8_CHARACTER_LITERALS 1
#define GO_NO_CXX17_ALLOW_CONSTANT_EVALUATION_FOR_ALL_NONTYPE_TEMPLATE_ARGUMENTS 1
#define GO_NO_CXX17_FOLD_EXPRESSIONS 1
#endif  // #if (GO_CLANG_VERSION < 30600)
#if (GO_CLANG_VERSION < 30500)
#define GO_NO_CXX17_TYPENAME_IN_A_TEMPLATE_TEMPLATE_PARAMETER 1
#define GO_NO_CXX17_REMOVING_TRIGRAPHS 1
#endif  // #if (GO_CLANG_VERSION < 30500)
#if (GO_CLANG_VERSION < 20500)
#define GO_NO_CXX17_STATIC_ASSERT_WITH_NO_MESSAGE 1
#define GO_NO_CXX17 1
#endif  // #if (GO_CLANG_VERSION < 20500)
#if defined(GO_CLANG_VERSION)
#define GO_NO_CXX17_STANDARDIZATION_OF_PARALLELISM_TS 1
#define GO_NO_CXX17_ELEMENTARY_STRING_CONVERSIONS 1
#define GO_NO_CXX17_MATHEMATICAL_SPECIAL_FUNCTIONS 1
#define GO_NO_CXX17_HARDWARE_INTERFERENCE_SIZE 1
#endif  // #if defined(GO_CLANG_VERSION)

// C++2a support
#if (GO_CLANG_VERSION < 80000)
#define GO_NO_CXX2A_CONST_MISMATCH_WITH_DEFAULTED_COPY_CONSTRUCTOR 1
#define GO_NO_CXX2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR 1
#define GO_NO_CXX2A_PROHIBIT_AGGREGATES_WITH_USER_DECLARED_CONSTRUCTORS 1
#define GO_NO_CXX2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS 1
#define GO_NO_CXX2A_CONSTEXPR_FOR_ALGORITHM_AND_UTILITY 1
#endif  // #if (GO_CLANG_VERSION < 80000)
#if (GO_CLANG_VERSION < 70000)
#define GO_NO_CXX2A_THREE_WAY_COMPARISON_OPERATOR_SUPPORT_COMPARE 1
#define GO_NO_CXX2A_STD_ENDIAN 1
#define GO_NO_CXX2A_CALENDAR_AND_TIMEZONE 1
#define GO_NO_CXX2A_STD_SPAN 1
#define GO_NO_CXX2A_VERSION 1
#endif  // #if (GO_CLANG_VERSION < 70000)
#if (GO_CLANG_VERSION < 60000)
#define GO_NO_CXX2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS 1
#define GO_NO_CXX2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS 1
#define GO_NO_CXX2A_ALLOW_LAMBDA_CAPTURE_ASSIGN_THIS 1
#define GO_NO_CXX2A_VA_OPT 1
#define GO_NO_CXX2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 1
#define GO_NO_CXX2A_STD_REMOVE_CVREF 1
#define GO_NO_CXX2A_STRING_PREFIX_AND_SUFFIX_CHECKING 1
#define GO_NO_CXX2A_UTILITY_TO_CONVERT_A_POINTER_TO_A_RAW_POINTER 1
#endif  // #if (GO_CLANG_VERSION < 60000)
#if (GO_CLANG_VERSION < 30400)
#define GO_NO_CXX2A_INTEGRATING_OUR_FEATURE_TEST_MACROS 1
#define GO_NO_CXX2A 1
#endif  // #if (GO_CLANG_VERSION < 30400)
#if defined(GO_CLANG_VERSION)
#define GO_NO_CXX2A_CONCEPTS 1
#define GO_NO_CXX2A_CONTRACTS 1
#define GO_NO_CXX2A_DESIGNATED_INITIALIZERS 1
#define GO_NO_CXX2A_TEMPLATE_PARAMETER_LIST_FOR_GENERIC_LAMBDAS 1
#define GO_NO_CXX2A_SIMPLIFYING_IMPLICIT_LAMBDA_CAPTURE 1
#define GO_NO_CXX2A_ADL_AND_FUNCTION_TEMPLATES_THAT_ARE_NOT_VISIBLE 1
#define GO_NO_CXX2A_THREE_WAY_COMPARISON_OPERATOR 1
#define GO_NO_CXX2A_ATTRIBUTE_NO_UNIQUE_ADDRESS 1
#define GO_NO_CXX2A_ATTRIBUTES_LIKELY_AND_UNLIKELY 1
#define GO_NO_CXX2A_TYPENAME_OPTIONAL 1
#define GO_NO_CXX2A_LESS_EAGER_INSTANTIATION_OF_CONSTEXPR_FUNCTIONS 1
#define GO_NO_CXX2A_CLASS_TYPES_IN_NON_TYPE_TEMPLATE_PARAMETERS 1
#define GO_NO_CXX2A_EXPLICIT_BOOL 1
#define GO_NO_CXX2A_CONSTEXPR_VIRTUAL_FUNCTION 1
#define GO_NO_CXX2A_EFFICIENT_SIZED_DELETE_FOR_VARIABLE_SIZED_CLASSES 1
#define GO_NO_CXX2A_ACCESS_CHECKING_ON_SPECIALIZATIONS 1
#define GO_NO_CXX2A_PACK_EXPANSION_IN_LAMBDA_INIT_CAPTURE 1
#define GO_NO_CXX2A_LAMBDAS_IN_UNEVALUATED_CONTEXTS 1
#define GO_NO_CXX2A_CONCEPTS_LIBRARY 1
#define GO_NO_CXX2A_STD_ATOMIC_REF 1
#define GO_NO_CXX2A_STD_BIT_CAST 1
#define GO_NO_CXX2A_EXTENDING_STD_MAKE_SHARED_TO_SUPPORT_ARRAYS 1
#define GO_NO_CXX2A_FLOATING_POINT_ATOMIC 1
#define GO_NO_CXX2A_SYNCHRONIZED_BUFFERED_OSTREAM 1
#define GO_NO_CXX2A_MORE_CONSTEXPR_FOR_COMPLEX 1
#endif  // #if defined(GO_CLANG_VERSION)

// C99 support
#if (GO_CLANG_VERSION < 20800)
#define GO_NO_C99_PREPROCESSOR 1
#endif  // #if (GO_CLANG_VERSION < 20800)

#endif  // defined(__clang__)

#endif  // #ifndef GO_CONFIG_COMPILER_CLANG_HPP_INCLUDED
