copy /B /V /Y .\msys-mingw\libs\boost_config\GO_libraries_boost_config_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_exception\GO_libraries_boost_exception_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_mvvm\GO_libraries_boost_mvvm_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_property\GO_libraries_boost_property_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_utility\GO_libraries_boost_utility_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\config\GO_libraries_std_config_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\exception\GO_libraries_std_exception_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\mvvm\GO_libraries_std_mvvm_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\property\GO_libraries_std_property_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\signals\GO_libraries_std_signals_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\utility\GO_libraries_std_utility_tests.exe .\bin\msys-mingw\.

copy /B /V /Y .\vc90\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc90\.

copy /B /V /Y .\vc100\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc100\.

copy /B /V /Y .\vc110\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc110\.

copy /B /V /Y .\vc120\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc120\.

copy /B /V /Y .\vc140\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc140\.

copy /B /V /Y .\vc141\libs\boost_config\Release\GO_libraries_boost_config_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_exception\Release\GO_libraries_boost_exception_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_mvvm\Release\GO_libraries_boost_mvvm_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_property\Release\GO_libraries_boost_property_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_utility\Release\GO_libraries_boost_utility_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\config\Release\GO_libraries_std_config_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\exception\Release\GO_libraries_std_exception_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\mvvm\Release\GO_libraries_std_mvvm_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\property\Release\GO_libraries_std_property_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\signals\Release\GO_libraries_std_signals_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\utility\Release\GO_libraries_std_utility_tests.exe .\bin\vc141\.
