@echo off

copy /B /V /Y .\msys-mingw\libs\boost_config\GO_boost_libraries_config_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_exception\GO_boost_libraries_diagnostics_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_exception\GO_boost_libraries_exception_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_mvvm\GO_boost_libraries_mvvm_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_property\GO_boost_libraries_property_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\boost_utility\GO_boost_libraries_utility_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_config\GO_std_libraries_config_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_exception\GO_std_libraries_diagnostics_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_exception\GO_std_libraries_exception_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_mvvm\GO_std_libraries_mvvm_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_property\GO_std_libraries_property_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_signals\GO_std_libraries_signals_tests.exe .\bin\msys-mingw\.
copy /B /V /Y .\msys-mingw\libs\std_utility\GO_std_libraries_utility_tests.exe .\bin\msys-mingw\.

copy /B /V /Y .\vc90\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc90\.
copy /B /V /Y .\vc90\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc90\.

copy /B /V /Y .\vc100\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc100\.
copy /B /V /Y .\vc100\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc100\.

copy /B /V /Y .\vc110\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc110\.
copy /B /V /Y .\vc110\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc110\.

copy /B /V /Y .\vc120\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc120\.
copy /B /V /Y .\vc120\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc120\.

copy /B /V /Y .\vc140\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc140\.
copy /B /V /Y .\vc140\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc140\.

copy /B /V /Y .\vc141\libs\boost_config\Release\GO_boost_libraries_config_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_exception\Release\GO_boost_libraries_diagnostics_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_exception\Release\GO_boost_libraries_exception_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_mvvm\Release\GO_boost_libraries_mvvm_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_property\Release\GO_boost_libraries_property_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\boost_utility\Release\GO_boost_libraries_utility_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_config\Release\GO_std_libraries_config_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_exception\Release\GO_std_libraries_diagnostics_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_exception\Release\GO_std_libraries_exception_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_mvvm\Release\GO_std_libraries_mvvm_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_property\Release\GO_std_libraries_property_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_signals\Release\GO_std_libraries_signals_tests.exe .\bin\vc141\.
copy /B /V /Y .\vc141\libs\std_utility\Release\GO_std_libraries_utility_tests.exe .\bin\vc141\.
