#ifndef GO_BOOST_CONFIG_COMPILER_CLANG_HPP_INCLUDED
#define GO_BOOST_CONFIG_COMPILER_CLANG_HPP_INCLUDED

//
//  clang.hpp
//
//  Copyright 2017-2021 Göran Orsander
//
//  This file is part of the GO.libraries.
//  Distributed under the GO Software License, Version 2.0.
//  See accompanying file LICENSE.md.
//

#include <go_boost/config.hpp>
#include <boost/config/helper_macros.hpp>

#ifdef BOOST_HAS_PRAGMA_ONCE
#pragma once
#endif  // #ifdef BOOST_HAS_PRAGMA_ONCE

#if defined(__clang__)

#define GO_BOOST_COMP_CLANG 1

#define GO_BOOST_CLANG_VERSION (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__)

// Use #pragma in macros
#define GO_BOOST_DO_PRAGMA(x) _Pragma (#x)
#define GO_BOOST_DO_PRAGMA_EX(x) GO_BOOST_DO_PRAGMA(x)

// Compiler message
#define GO_BOOST_MESSAGE(_message_) GO_BOOST_DO_PRAGMA_EX(GCC warning BOOST_PP_STRINGIZE(_message_))

// C++ keyword typename support
#define GO_BOOST_TYPENAME typename
#define GO_BOOST_CPP_TYPENAME_REQUIRED 1

// C++ issue workarounds
#define GO_BOOST_CHAR_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_BOOST_WCHAR_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_BOOST_CHAR16_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1
#define GO_BOOST_CHAR32_T_ILLEGAL_BYTE_SEQUENCE_ISSUE 1

// C++11 support
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX11 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)

// C++11 language support
#if (GO_BOOST_CLANG_VERSION < 30300)
#define GO_BOOST_NO_CXX11_THREAD_LOCAL_STORAGE 1
#define GO_BOOST_NO_CXX11_ATTRIBUTES 1
#define GO_BOOST_NO_CXX11_INHERITING_CONSTRUCTORS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30300)
#if (GO_BOOST_CLANG_VERSION < 30100)
#define GO_BOOST_NO_CXX11_ATOMIC_OPERATIONS 1
#define GO_BOOST_NO_CXX11_CONSTEXPR 1
#define GO_BOOST_NO_CXX11_FORWARD_ENUM_DECLARATIONS 1
#define GO_BOOST_NO_CXX11_INITIALIZER_LISTS 1
#define GO_BOOST_NO_CXX11_LAMBDA_EXPRESSIONS 1
#define GO_BOOST_NO_CXX11_USER_DEFINED_LITERALS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30100)
#if (GO_BOOST_CLANG_VERSION < 30000)
#define GO_BOOST_NO_CXX11_ALIGNAS 1
#define GO_BOOST_NO_CXX11_COMPILER_SUPPORT_FOR_TYPE_TRAITS 1
#define GO_BOOST_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS 1
#define GO_BOOST_NO_CXX11_DELEGATING_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS 1
#define GO_BOOST_NO_CXX11_NOEXCEPT 1
#define GO_BOOST_NO_CXX11_NON_STATIC_DATA_MEMBER_INITIALIZERS 1
#define GO_BOOST_NO_CXX11_RANGE_FOR_LOOP 1
#define GO_BOOST_NO_CXX11_TEMPLATE_ALIASES 1
#define GO_BOOST_NO_CXX11_UNICODE_STRING_LITERALS 1
#define GO_BOOST_NO_CXX11_UNRESTRICTED_UNIONS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30000)
#if (GO_BOOST_CLANG_VERSION < 20900)
#define GO_BOOST_NO_CXX11_ALIGNOF 1
#define GO_BOOST_NO_CXX11_CHAR16_T_AND_CHAR32_T 1
#define GO_BOOST_NO_CXX11_DECLTYPE 1
#define GO_BOOST_NO_CXX11_DYNAMIC_INITIALIZATION_AND_DESTRUCTION_WITH_CONCURRENCY_MAGIC_STATICS 1
#define GO_BOOST_NO_CXX11_EXPRESSION_SFINAE 1
#define GO_BOOST_NO_CXX11_EXTENDED_FRIEND_DECLARATIONS 1
#define GO_BOOST_NO_CXX11_INLINE_NAMESPACES 1
#define GO_BOOST_NO_CXX11_LOCAL_AND_UNNAMED_TYPES_AS_TEMPLATE_PARAMETERS 1
#define GO_BOOST_NO_CXX11_NULLPTR 1
#define GO_BOOST_NO_CXX11_OVERRIDE_AND_FINAL 1
#define GO_BOOST_NO_CXX11_REF_QUALIFIERS 1
#define GO_BOOST_NO_CXX11_STATIC_ASSERT 1
#define GO_BOOST_NO_CXX11_STRONGLY_TYPED_ENUM 1
#define GO_BOOST_NO_CXX11_TRAILING_FUNCTION_RETURN_TYPES 1
#define GO_BOOST_NO_CXX11_VARIADIC_TEMPLATES 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20900)
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX11_AUTO 1
#define GO_BOOST_NO_CXX11_C99_PREPROCESSOR 1
#define GO_BOOST_NO_CXX11_EXTERN_TEMPLATE 1
#define GO_BOOST_NO_CXX11_LONG_LONG 1
#define GO_BOOST_NO_CXX11_RAW_STRING_LITERALS 1
#define GO_BOOST_NO_CXX11_RIGHT_ANGLE_BRACKETS 1
#define GO_BOOST_NO_CXX11_RVALUE_REFERENCES 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)
#if defined(GO_BOOST_CLANG_VERSION)
#define GO_BOOST_NO_CXX11_GARBAGE_COLLECTION_AND_REACHABILITY_BASED_LEAK_DETECTION 1
#endif  // #if defined(GO_BOOST_CLANG_VERSION)

// C++11 library support
#if (GO_BOOST_CLANG_VERSION < 30800)
#define GO_BOOST_NO_CXX11_MONEY_TIME_AND_HEXFLOAT_IO_MANIPULATORS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30800)
#if (GO_BOOST_CLANG_VERSION < 30400)
#define GO_BOOST_NO_CXX11_GARBAGE_COLLECTION_AND_REACHABILITY_BASED_LEAK_DETECTION_LIBRARY_SUPPORT_NO_OP 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30400)
#if (GO_BOOST_CLANG_VERSION < 30000)
#define GO_BOOST_NO_CXX11_TYPE_TRAITS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30000)

// C++11 cross platform support
#if (GO_BOOST_CLANG_VERSION < 30000)
#define GO_BOOST_NO_CXX11_TYPE_ALIASES 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30000)
#if (GO_BOOST_CLANG_VERSION < 20900)
#define GO_BOOST_NO_CXX11_CHAR16_T 1
#define GO_BOOST_NO_CXX11_CHAR32_T 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20900)
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX11_STATIC_CONST_DATA_MEMBER_INSIDE_CLASS_DEFINITION 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX11_LOCALTIME_S 1

#if defined(GO_BOOST_NO_CXX11_CONSTEXPR)
#define GO_BOOST_CONSTEXPR
#else
#define GO_BOOST_CONSTEXPR constexpr
#endif  // #if defined(GO_BOOST_NO_CXX11_CONSTEXPR)

#if defined(GO_BOOST_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS) || defined(GO_BOOST_COMP_MSVC_VC120)
#define GO_BOOST_DEFAULT_CONSTRUCTOR {}
#define GO_BOOST_DEFAULT_DESTRUCTOR {}
#else
#define GO_BOOST_DEFAULT_CONSTRUCTOR = default;
#define GO_BOOST_DEFAULT_DESTRUCTOR = default;
#endif  // #if defined(GO_BOOST_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS)

#if defined(GO_BOOST_NO_CXX11_NOEXCEPT)
#define GO_BOOST_NOEXCEPT
#define GO_BOOST_NOEXCEPT_OR_NOTHROW throw()
#define GO_BOOST_NOEXCEPT_IF(_predicate_)
#define GO_BOOST_NOEXCEPT_EXPR(_expression_) false
#else
#define GO_BOOST_NOEXCEPT noexcept
#define GO_BOOST_NOEXCEPT_OR_NOTHROW noexcept
#define GO_BOOST_NOEXCEPT_IF(_predicate_) noexcept((_predicate_))
#define GO_BOOST_NOEXCEPT_EXPR(_expression_) noexcept((_expression_))
#endif  // #if defined(GO_BOOST_NO_CXX11_NOEXCEPT)

#if defined(GO_BOOST_NO_CXX11_NULLPTR)
#define GO_BOOST_NULLPTR NULL
#else
#define GO_BOOST_NULLPTR nullptr
#endif  // #if defined(GO_BOOST_NO_CXX11_NULLPTR)

#if defined(GO_BOOST_NO_CXX11_OVERRIDE_AND_FINAL)
#define GO_BOOST_FINAL
#define GO_BOOST_OVERRIDE
#else
#define GO_BOOST_FINAL final
#define GO_BOOST_OVERRIDE override
#endif  // #if defined(GO_BOOST_NO_CXX11_OVERRIDE_AND_FINAL)

#if defined(GO_BOOST_NO_CXX11_TEMPLATE_ALIASES)
#define GO_BOOST_USING(_alias_, _type_) typedef _type_ _alias_
#else
#define GO_BOOST_USING(_alias_, _type_) using _alias_ = _type_;
#endif  // #if defined(GO_BOOST_NO_CXX11_TEMPLATE_ALIASES)

// C++14 support
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX14 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)

// C++14 language support
#if (GO_BOOST_CLANG_VERSION < 30400)
#define GO_BOOST_NO_CXX14_CLARIFYING_MEMORY_ALLOCATION_AVOIDING_FUSING_ALLOCATIONS
#define GO_BOOST_NO_CXX14_DECLTYPE_AUTO_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTIONS
#define GO_BOOST_NO_CXX14_DEPRECATED_ATTRIBUTE
#define GO_BOOST_NO_CXX14_EXTENDED_CONSTEXPR
#define GO_BOOST_NO_CXX14_GENERIC_POLYMORPHIC_LAMBDA_EXPRESSIONS
#define GO_BOOST_NO_CXX14_INITIALIZED_GENERALIZED_LAMBDA_CAPTURES_INIT_CAPTURE
#define GO_BOOST_NO_CXX14_SINGLE_QUOTE_AS_DIGIT_SEPARATOR
#define GO_BOOST_NO_CXX14_SIZED_DEALLOCATION
#define GO_BOOST_NO_CXX14_TWEAKED_WORDING_FOR_CONTEXTUAL_CONVERSIONS
#define GO_BOOST_NO_CXX14_VARIABLE_TEMPLATES
#endif  // #if (GO_BOOST_CLANG_VERSION < 30400)
#if (GO_BOOST_CLANG_VERSION < 30300)
#define GO_BOOST_NO_CXX14_MEMBER_INITIALIZERS_AND_AGGREGATES_NSDMI
#endif  // #if (GO_BOOST_CLANG_VERSION < 30300)
#if (GO_BOOST_CLANG_VERSION < 20900)
#define GO_BOOST_NO_CXX14_BINARY_LITERALS
#endif  // #if (GO_BOOST_CLANG_VERSION < 20900)

// C++14 library support
#if (GO_BOOST_CLANG_VERSION < 30400)
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_ARRAY
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_CHRONO
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_COMPLEX
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_INITIALIZER_LIST_UTILITY_AND_TUPLE
#define GO_BOOST_NO_CXX14_DUAL_RANGE_STD_EQUAL_STD_IS_PERMUTATION_STD_MISMATCH
#define GO_BOOST_NO_CXX14_FIXING_CONSTEXPR_MEMBER_FUNCTIONS_WITHOUT_CONST
#define GO_BOOST_NO_CXX14_HETEROGENEOUS_ASSOCIATIVE_LOOKUP
#define GO_BOOST_NO_CXX14_IMPROVED_STD_INTEGRAL_CONSTANT
#define GO_BOOST_NO_CXX14_NULL_FORWARD_ITERATORS
#define GO_BOOST_NO_CXX14_STD_EXCHANGE
#define GO_BOOST_NO_CXX14_STD_GET_T
#define GO_BOOST_NO_CXX14_STD_INTEGER_SEQUENCE
#define GO_BOOST_NO_CXX14_STD_QUOTED
#define GO_BOOST_NO_CXX14_STD_SHARED_TIMED_MUTEX
#define GO_BOOST_NO_CXX14_USER_DEFINED_LITERALS_FOR_CHRONO_AND_STRING
#endif  // #if (GO_BOOST_CLANG_VERSION < 30400)
#if defined(GO_BOOST_CLANG_VERSION)
#define GO_BOOST_NO_CXX14_STD_RESULT_OF_AND_SFINAE
#endif  // #if defined(GO_BOOST_CLANG_VERSION)

// C++14 cross platform support
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_CXX14_ARGUMENT_DEPENDENT_LOOKUP 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)

#if defined(GO_BOOST_NO_CXX14_EXTENDED_CONSTEXPR)
#define GO_BOOST_EXTENDED_CONSTEXPR
#else
#define GO_BOOST_EXTENDED_CONSTEXPR constexpr
#endif  // #if defined(GO_NO_CXX11_CONSTEXPR)

// C++17 support
#if (GO_BOOST_CLANG_VERSION < 20500)
#define GO_BOOST_NO_CXX17 1
#else
#ifndef GO_BOOST_NO_STD_AUTO_PTR
#define GO_BOOST_NO_STD_AUTO_PTR 1
#endif  // #ifndef GO_BOOST_NO_STD_AUTO_PTR
#endif  // #if (GO_BOOST_CLANG_VERSION < 20500)

// C++17 language support
#if (GO_BOOST_CLANG_VERSION < 60000)
#define GO_BOOST_NO_CXX17_REPLACEMENT_OF_CLASS_OBJECTS_CONTAINING_REFERENCE_MEMBERS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 60000)
#if (GO_BOOST_CLANG_VERSION < 50000)
#define GO_BOOST_NO_CXX17_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 1
#define GO_BOOST_NO_CXX17_CONSTEXPR_LAMBDA_EXPRESSIONS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 50000)
#if (GO_BOOST_CLANG_VERSION < 40000)
#define GO_BOOST_NO_CXX17_DR_MATCHING_OF_TEMPLATE_TEMPLATE_ARGUMENTS_EXCLUDES_COMPATIBLE_TEMPLATES 1
#define GO_BOOST_NO_CXX17_DYNAMIC_MEMORY_ALLOCATION_FOR_OVER_ALIGNED_DATA 1
#define GO_BOOST_NO_CXX17_GUARANTEED_COPY_ELISION 1
#define GO_BOOST_NO_CXX17_MAKE_EXCEPTION_SPECIFICATIONS_PART_OF_THE_TYPE_SYSTEM 1
#define GO_BOOST_NO_CXX17_NON_TYPE_TEMPLATE_PARAMETERS_WITH_AUTO_TYPE 1
#define GO_BOOST_NO_CXX17_PACK_EXPANSIONS_IN_USING_DECLARATIONS 1
#define GO_BOOST_NO_CXX17_REMOVING_DEPRECATED_EXCEPTION_SPECIFICATIONS_FROM_CXX17 1
#define GO_BOOST_NO_CXX17_STRICTER_EXPRESSION_EVALUATION_ORDER 1
#define GO_BOOST_NO_CXX17_STRUCTURED_BINDINGS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 40000)
#if (GO_BOOST_CLANG_VERSION < 30900)
#define GO_BOOST_NO_CXX17_AGGREGATE_INITIALIZATION_OF_CLASSES_WITH_BASE_CLASSES 1
#define GO_BOOST_NO_CXX17_CONSTEXPR_IF_STATEMENTS 1
#define GO_BOOST_NO_CXX17_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR 1
#define GO_BOOST_NO_CXX17_DIRECT_LIST_INITIALIZATION_OF_ENUMERATIONS 1
#define GO_BOOST_NO_CXX17_DR_NEW_SPECIFICATION_FOR_INHERITING_CONSTRUCTORS_DR1941_ET_AL 1
#define GO_BOOST_NO_CXX17_FALLTHROUGH_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_IGNORE_UNKNOWN_ATTRIBUTES 1
#define GO_BOOST_NO_CXX17_INIT_STATEMENTS_FOR_IF_AND_SWITCH 1
#define GO_BOOST_NO_CXX17_INLINE_VARIABLES 1
#define GO_BOOST_NO_CXX17_LAMBDA_CAPTURE_OF_THIS_DEREFERENCED_BY_VALUE 1
#define GO_BOOST_NO_CXX17_MAYBE_UNUSED_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_NODISCARD_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_UNARY_FOLD_EXPRESSIONS_AND_EMPTY_PARAMETER_PACKS 1
#define GO_BOOST_NO_CXX17_USING_ATTRIBUTE_NAMESPACES_WITHOUT_REPETITION 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30900)
#if (GO_BOOST_CLANG_VERSION < 30800)
#define GO_BOOST_NO_CXX17_NEW_AUTO_RULES_FOR_DIRECT_LIST_INITIALIZATION 1
#define GO_BOOST_NO_CXX17_REMOVE_DEPRECATED_OPERATOR_PLUS_PLUS_BOOL 1
#define GO_BOOST_NO_CXX17_REMOVE_DEPRECATED_USE_OF_THE_REGISTER_KEYWORD 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30800)
#if (GO_BOOST_CLANG_VERSION < 30600)
#define GO_BOOST_NO_CXX17_ALLOW_CONSTANT_EVALUATION_FOR_ALL_NON_TYPE_TEMPLATE_ARGUMENTS 1
#define GO_BOOST_NO_CXX17_ATTRIBUTES_FOR_NAMESPACES_AND_ENUMERATORS 1
#define GO_BOOST_NO_CXX17_FOLD_EXPRESSIONS 1
#define GO_BOOST_NO_CXX17_NESTED_NAMESPACE_DEFINITION 1
#define GO_BOOST_NO_CXX17_U8_CHARACTER_LITERALS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30600)
#if (GO_BOOST_CLANG_VERSION < 30500)
#define GO_BOOST_NO_CXX17_REMOVING_TRIGRAPHS 1
#define GO_BOOST_NO_CXX17_TYPENAME_IN_A_TEMPLATE_TEMPLATE_PARAMETER 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30500)
#if (GO_BOOST_CLANG_VERSION < 20500)
#define GO_BOOST_NO_CXX17_STATIC_ASSERT_WITH_NO_MESSAGE 1
#define GO_BOOST_NO_CXX17___HAS_INCLUDE_IN_PREPROCESSOR_CONDITIONALS 1
#define GO_BOOST_NO_CXX17_HEXADECIMAL_FLOATING_POINT_LITERALS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20500)

// C++17 library support
#if (GO_BOOST_CLANG_VERSION < 80000)
#define GO_BOOST_NO_CXX17_SPLICING_MAPS_AND_SETS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 80000)
#if (GO_BOOST_CLANG_VERSION < 70000)
#define GO_BOOST_NO_CXX17_CXX17_SHOULD_REFER_TO_C11_INSTEAD_OF_C99 1
#define GO_BOOST_NO_CXX17_ELEMENTARY_STRING_CONVERSIONS 1
#define GO_BOOST_NO_CXX17_FILE_SYSTEM_LIBRARY 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 70000)
#if (GO_BOOST_CLANG_VERSION < 60000)
#define GO_BOOST_NO_CXX17_STD_HAS_UNIQUE_OBJECT_REPRESENTATIONS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 60000)
#if (GO_BOOST_CLANG_VERSION < 50000)
#define GO_BOOST_NO_CXX17_STD_BYTE 1
#define GO_BOOST_NO_CXX17_STD_IS_AGGREGATE 1
#define GO_BOOST_NO_CXX17_STD_SCOPED_LOCK 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 50000)
#if (GO_BOOST_CLANG_VERSION < 40000)
#define GO_BOOST_NO_CXX17_IMPROVING_STD_PAIR_AND_STD_TUPLE 1
#define GO_BOOST_NO_CXX17_STD_ANY 1
#define GO_BOOST_NO_CXX17_STD_GCD_AND_STD_LCM 1
#define GO_BOOST_NO_CXX17_STD_OPTIONAL 1
#define GO_BOOST_NO_CXX17_STD_STRING_VIEW 1
#define GO_BOOST_NO_CXX17_STD_VARIANT 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 40000)
#if (GO_BOOST_CLANG_VERSION < 30900)
#define GO_BOOST_NO_CXX17_NOTHROW_SWAPPABLE_TRAITS 1
#define GO_BOOST_NO_CXX17_STD_CLAMP 1
#define GO_BOOST_NO_CXX17_STD_MAKE_FROM_TUPLE 1
#define GO_BOOST_NO_CXX17_STD_NOT_FN 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30900)
#if (GO_BOOST_CLANG_VERSION < 30800)
#define GO_BOOST_NO_CXX17_LOGICAL_OPERATOR_TYPE_TRAITS 1
#define GO_BOOST_NO_CXX17_TYPE_TRAITS_VARIABLE_TEMPLATES 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30800)
#if (GO_BOOST_CLANG_VERSION < 30700)
#define GO_BOOST_NO_CXX17_STD_BOOL_CONSTANT 1
#define GO_BOOST_NO_CXX17_STD_SHARED_MUTEX_UNTIMED 1
#define GO_BOOST_NO_CXX17_STD_UNCAUGHT_EXCEPTIONS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30700)
#if (GO_BOOST_CLANG_VERSION < 30600)
#define GO_BOOST_NO_CXX17_STD_SIZE_STD_EMPTY_AND_STD_DATA 1
#define GO_BOOST_NO_CXX17_STD_VOID_T 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30600)
#if defined(GO_BOOST_CLANG_VERSION)
#define GO_BOOST_NO_CXX17_HARDWARE_INTERFERENCE_SIZE 1
#define GO_BOOST_NO_CXX17_MATHEMATICAL_SPECIAL_FUNCTIONS 1
#define GO_BOOST_NO_CXX17_POLYMORPHIC_MEMORY_RESOURCES 1
#define GO_BOOST_NO_CXX17_STANDARDIZATION_OF_PARALLELISM_TS 1
#define GO_BOOST_NO_CXX17_STD_SHARED_PTR_AND_STD_WEAK_PTR_WITH_ARRAY_SUPPORT 1
#endif  // #if defined(GO_BOOST_CLANG_VERSION)

// C++17 cross platform support

// C++2a support
#if (GO_BOOST_CLANG_VERSION < 30400)
#define GO_BOOST_NO_CXX2A 1
#else
#ifndef GO_BOOST_NO_STD_AUTO_PTR
#define GO_BOOST_NO_STD_AUTO_PTR 1
#endif  // #ifndef GO_BOOST_NO_STD_AUTO_PTR
#endif  // #if (GO_BOOST_CLANG_VERSION < 30400)

// C++2a language support
#if (GO_BOOST_CLANG_VERSION < 100000)
#define GO_BOOST_NO_CXX2A_CONSTINIT 1
#define GO_BOOST_NO_CXX2A_DESIGNATED_INITIALIZERS 1
#define GO_BOOST_NO_CXX2A_TRIVIAL_DEFAULT_INITIALIZATION_IN_CONSTEXPR_FUNCTIONS 1
#define GO_BOOST_NO_CXX2A_UNEVALUATED_ASM_DECLARATION_IN_CONSTEXPR_FUNCTIONS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 100000)
#if (GO_BOOST_CLANG_VERSION < 90000)
#define GO_BOOST_NO_CXX2A___VA_OPT__ 1
#define GO_BOOST_NO_CXX2A_ADL_AND_FUNCTION_TEMPLATES_THAT_ARE_NOT_VISIBLE 1
#define GO_BOOST_NO_CXX2A_ATTRIBUTE_NO_UNIQUE_ADDRESS 1
#define GO_BOOST_NO_CXX2A_CHANGING_THE_ACTIVE_MEMBER_OF_A_UNION_INSIDE_CONSTEXPR 1
#define GO_BOOST_NO_CXX2A_CONSTEXPR_DYNAMIC_CAST_AND_POLYMORPHIC_TYPEID 1
#define GO_BOOST_NO_CXX2A_CONSTEXPR_VIRTUAL_FUNCTION 1
#define GO_BOOST_NO_CXX2A_DEPRECATE_COMMA_OPERATOR_IN_SUBSCRIPTS 1
#define GO_BOOST_NO_CXX2A_DR_ARRAY_SIZE_DEDUCTION_IN_NEW_EXPRESSIONS 1
#define GO_BOOST_NO_CXX2A_DR_EXPLICITLY_DEFAULTED_FUNCTIONS_WITH_DIFFERENT_EXCEPTION_SPECIFICATIONS 1
#define GO_BOOST_NO_CXX2A_DR_NODISCARD_FOR_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX2A_EXPLICIT_BOOL 1
#define GO_BOOST_NO_CXX2A_NODISCARD_WITH_MESSAGE 1
#define GO_BOOST_NO_CXX2A_PACK_EXPANSION_IN_LAMBDA_INIT_CAPTURE 1
#define GO_BOOST_NO_CXX2A_SIGNED_INTEGERS_ARE_TWOS_COMPLEMENT 1
#define GO_BOOST_NO_CXX2A_STD_IS_CONSTANT_EVALUATED 1
#define GO_BOOST_NO_CXX2A_TEMPLATE_PARAMETER_LIST_FOR_GENERIC_LAMBDAS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 90000)
#if (GO_BOOST_CLANG_VERSION < 80000)
#define GO_BOOST_NO_CXX2A_CONST_MISMATCH_WITH_DEFAULTED_COPY_CONSTRUCTOR 1
#define GO_BOOST_NO_CXX2A_CONSTEXPR_TRY_CATCH_BLOCKS 1
#define GO_BOOST_NO_CXX2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS 1
#define GO_BOOST_NO_CXX2A_DR_ALLOW_STRUCTURED_BINDINGS_TO_ACCESSIBLE_MEMBERS 1
#define GO_BOOST_NO_CXX2A_DR_RELAXING_THE_STRUCTURED_BINDINGS_CUSTOMIZATION_POINT_FINDING_RULES 1
#define GO_BOOST_NO_CXX2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR 1
#define GO_BOOST_NO_CXX2A_NESTED_INLINE_NAMESPACES 1
#define GO_BOOST_NO_CXX2A_PROHIBIT_AGGREGATES_WITH_USER_DECLARED_CONSTRUCTORS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 80000)
#if (GO_BOOST_CLANG_VERSION < 70000)
#define GO_BOOST_NO_CXX2A_CHAR8_T 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 70000)
#if (GO_BOOST_CLANG_VERSION < 60000)
#define GO_BOOST_NO_CXX2A_ALLOW_LAMBDA_CAPTURE_ASSIGN_THIS 1
#define GO_BOOST_NO_CXX2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS 1
#define GO_BOOST_NO_CXX2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS 1
#define GO_BOOST_NO_CXX2A_DESTROYING_OPERATOR_DELETE 1
#define GO_BOOST_NO_CXX2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 60000)
#if (GO_BOOST_CLANG_VERSION < 30400)
#define GO_BOOST_NO_CXX2A_STRONGER_UNICODE_REQUIREMENTS 1
#define GO_BOOST_NO_CXX2A_INTEGRATING_FEATURE_TEST_MACROS 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 30400)
#if defined(GO_BOOST_CLANG_VERSION)
#define GO_BOOST_NO_CXX2A_ACCESS_CHECKING_ON_SPECIALIZATIONS 1
#define GO_BOOST_NO_CXX2A_ATTRIBUTES_LIKELY_AND_UNLIKELY 1
#define GO_BOOST_NO_CXX2A_CLASS_TYPES_IN_NON_TYPE_TEMPLATE_PARAMETERS 1
#define GO_BOOST_NO_CXX2A_CONCEPTS 1
#define GO_BOOST_NO_CXX2A_CONSISTENCY_IMPROVEMENTS_FOR_COMPARISONS 1
#define GO_BOOST_NO_CXX2A_COROUTINES 1
#define GO_BOOST_NO_CXX2A_DEPRECATE_IMPLICIT_CAPTURE_OF_THIS_VIA_ASSIGN 1
#define GO_BOOST_NO_CXX2A_DEPRECATING_SOME_USES_OF_VOLATILE 1
#define GO_BOOST_NO_CXX2A_DR_IMPLICIT_MOVE_FOR_MORE_LOCAL_OBJECTS_AND_RVALUE_REFERENCES 1
#define GO_BOOST_NO_CXX2A_DR_RELAXING_THE_RANGE_FOR_LOOP_CUSTOMIZATION_POINT_FINDING_RULES 1
#define GO_BOOST_NO_CXX2A_IMMEDIATE_FUNCTIONS 1
#define GO_BOOST_NO_CXX2A_LAMBDA_CAPTURE_AND_STORAGE_CLASS_SPECIFIERS_OF_STRUCTURED_BINDINGS 1
#define GO_BOOST_NO_CXX2A_LAMBDAS_IN_UNEVALUATED_CONTEXTS 1
#define GO_BOOST_NO_CXX2A_LESS_EAGER_INSTANTIATION_OF_CONSTEXPR_FUNCTIONS 1
#define GO_BOOST_NO_CXX2A_MAKE_TYPENAME_MORE_OPTIONAL 1
#define GO_BOOST_NO_CXX2A_MODULES 1
#define GO_BOOST_NO_CXX2A_MORE_CONSTEXPR_CONTAINERS 1
#define GO_BOOST_NO_CXX2A_PARENTHESIZED_INITIALIZATION_OF_AGGREGATES 1
#define GO_BOOST_NO_CXX2A_PERMIT_CONVERSIONS_TO_ARRAYS_OF_UNKNOWN_BOUND 1
#define GO_BOOST_NO_CXX2A_SIMPLIFYING_IMPLICIT_LAMBDA_CAPTURE 1
#define GO_BOOST_NO_CXX2A_THREE_WAY_COMPARE_NOT_EQUAL_AND_EQUAL 1
#define GO_BOOST_NO_CXX2A_THREE_WAY_COMPARISON_OPERATOR 1
#define GO_BOOST_NO_CXX2A_YET_ANOTHER_APPROACH_FOR_CONSTRAINED_DECLARATIONS 1
#endif  // #if defined(GO_BOOST_CLANG_VERSION)

// C++2a library support
#if (GO_BOOST_CLANG_VERSION < 100000)
#endif  // #if (GO_BOOST_CLANG_VERSION < 100000)
#if (GO_BOOST_CLANG_VERSION < 90000)
#define GO_BOOST_NO_CXX2A_MAKE_STD_MEMORY_ORDER_A_SCOPED_ENUMERATION
#define GO_BOOST_NO_CXX2A_STD_DESTROYING_DELETE
#define GO_BOOST_NO_CXX2A_STD_IS_NOTHROW_CONVERTIBLE
#define GO_BOOST_NO_CXX2A_A_SANE_STD_VARIANT_CONVERTING_CONSTRUCTOR
#define GO_BOOST_NO_CXX2A_STD_LERP_AND_STD_MIDPOINT
#define GO_BOOST_NO_CXX2A_USABILITY_ENHANCEMENTS_FOR_STD_SPAN
#define GO_BOOST_NO_CXX2A_STD_SSIZE_AND_UNSIGNED_EXTENT_FOR_STD_SPAN
#define GO_BOOST_NO_CXX2A_TRAITS_FOR_BOUNDED_AND_UNBOUNDED_ARRAYS
#define GO_BOOST_NO_CXX2A_BIT_OPERATIONS
#endif  // #if (GO_BOOST_CLANG_VERSION < 90000)
#if (GO_BOOST_CLANG_VERSION < 80000)
#define GO_BOOST_NO_CXX2A_CONSTEXPR_FOR_ALGORITHM_AND_UTILITY
#define GO_BOOST_NO_CXX2A_STD_BASIC_STRING_RESERVE_SHOULD_NOT_SHRINK
#define GO_BOOST_NO_CXX2A_STD_TYPE_IDENTITY
#define GO_BOOST_NO_CXX2A_CONSTEXPR_COMPARISON_OPERATORS_FOR_STD_ARRAY
#define GO_BOOST_NO_CXX2A_STD_UNWRAP_REF_DECAY_AND_STD_UNWRAP_REFERENCE
#define GO_BOOST_NO_CXX2A_STD_REFERENCE_WRAPPER_FOR_INCOMPLETE_TYPES
#define GO_BOOST_NO_CXX2A_FIXING_INPUT_STREAM_OPERATOR_BASIC_ISTREAM_REF_CHART_POINTER
#define GO_BOOST_NO_CXX2A_DR_STD_VARIANT_AND_STD_OPTIONAL_SHOULD_PROPAGATE_COPY_MOVE_TRIVIALITY
#define GO_BOOST_NO_CXX2A_CHRONO_ZERO_MIN_AND_MAX_SHOULD_BE_NOEXCEPT
#define GO_BOOST_NO_CXX2A_CONSTEXPR_IN_STD_POINTER_TRAITS
#define GO_BOOST_NO_CXX2A_REMOVE_COMPARISON_OPERATORS_OF_STD_SPAN
#define GO_BOOST_NO_CXX2A_CONSISTENT_CONTAINER_ERASURE
#endif  // #if (GO_BOOST_CLANG_VERSION < 80000)
#if (GO_BOOST_CLANG_VERSION < 70000)
#define GO_BOOST_NO_CXX2A_STD_ENDIAN
#define GO_BOOST_NO_CXX2A_LIBRARY_SUPPORT_FOR_OPERATOR_THREE_WAY_COMPARE
#define GO_BOOST_NO_CXX2A_STD_SPAN
#define GO_BOOST_NO_CXX2A_VERSION
#endif  // #if (GO_BOOST_CLANG_VERSION < 70000)
#if (GO_BOOST_CLANG_VERSION < 60000)
#define GO_BOOST_NO_CXX2A_STRING_PREFIX_AND_SUFFIX_CHECKING
#define GO_BOOST_NO_CXX2A_STD_REMOVE_CVREF
#define GO_BOOST_NO_CXX2A_UTILITY_TO_CONVERT_A_POINTER_TO_A_RAW_POINTER
#define GO_BOOST_NO_CXX2A_STD_FUNCTIONS_MOVE_CONSTRUCTOR_SHOULD_BE_NOEXCEPT
#endif  // #if (GO_BOOST_CLANG_VERSION < 60000)
#if defined(GO_BOOST_CLANG_VERSION)
#define GO_BOOST_NO_CXX2A_EXTENDING_STD_MAKE_SHARED_TO_SUPPORT_ARRAYS
#define GO_BOOST_NO_CXX2A_FLOATING_POINT_ATOMIC
#define GO_BOOST_NO_CXX2A_SYNCHRONIZED_BUFFERED_OSTREAM
#define GO_BOOST_NO_CXX2A_MORE_CONSTEXPR_FOR_COMPLEX
#define GO_BOOST_NO_CXX2A_NODISCARD_IN_THE_STANDARD_LIBRARY
#define GO_BOOST_NO_CXX2A_USING_STD_MOVE_IN_NUMERIC_ALGORITHMS
#define GO_BOOST_NO_CXX2A_ATOMIC_STD_SHARED_PTR_AND_STD_WEAK_PTR
#define GO_BOOST_NO_CXX2A_CALENDAR_AND_TIMEZONE
#define GO_BOOST_NO_CXX2A_COMPARING_UNORDERED_CONTAINERS
#define GO_BOOST_NO_CXX2A_CONSTEXPRITERATOR_REQUIREMENTS
#define GO_BOOST_NO_CXX2A_STD_ATOMIC_REF
#define GO_BOOST_NO_CXX2A_CONTAINS_MEMBER_FUNCTION_OF_ASSOCIATIVE_CONTAINERS
#define GO_BOOST_NO_CXX2A_DR_GUARANTEED_COPY_ELISION_FOR_PIECEWISE_CONSTRUCTION
#define GO_BOOST_NO_CXX2A_STD_BIT_CAST
#define GO_BOOST_NO_CXX2A_INTEGRAL_POWER_OF_2_OPERATIONS
#define GO_BOOST_NO_CXX2A_IMPROVING_THE_RETURN_VALUE_OF_ERASE_LIKE_ALGORITHMS
#define GO_BOOST_NO_CXX2A_ADD_SHIFT_TO_ALGORITHM
#define GO_BOOST_NO_CXX2A_CONSTEXPR_FOR_STD_SWAP_AND_SWAP_RELATED_FUNCTIONS
#define GO_BOOST_NO_CXX2A_CONCEPTS_LIBRARY
#define GO_BOOST_NO_CXX2A_STD_BIND_FRONT
#define GO_BOOST_NO_CXX2A_LIBRARY_SUPPORT_FOR_CHAR8_T
#define GO_BOOST_NO_CXX2A_UTILITY_FUNCTIONS_TO_IMPLEMENT_USES_ALLOCATOR_CONSTRUCTION
#define GO_BOOST_NO_CXX2A_THE_ONE_RANGES_PROPOSAL
#define GO_BOOST_NO_CXX2A_HETEROGENEOUS_LOOKUP_FOR_UNORDERED_CONTAINERS
#define GO_BOOST_NO_CXX2A_STD_ASSUME_ALIGNED
#define GO_BOOST_NO_CXX2A_MAKE_STATEFUL_ALLOCATOR_PROPAGATION_MORE_CONSISTENT_FOR_OPERATOR_PLUS_BASIC_STRING
#define GO_BOOST_NO_CXX2A_DR_MAKE_CREATE_DIRECTORY_INTUITIVE
#define GO_BOOST_NO_CXX2A_STD_SOURCE_LOCATION
#endif  // #if defined(GO_BOOST_CLANG_VERSION)

// C++2a cross platform support

// C99 support
#if (GO_BOOST_CLANG_VERSION < 20800)
#define GO_BOOST_NO_C99_PREPROCESSOR 1
#endif  // #if (GO_BOOST_CLANG_VERSION < 20800)

// Treat some warnings as error
//#pragma GCC diagnostic error "-Wfoo"

// Suppress warnings
#if defined (GO_BOOST_ENABLE_SUPPRESS_WARNINGS)

#define GO_BOOST_BEGIN_SUPPRESS_ALL_WARNINGS \
_Pragma("GCC diagnostic push") \
_Pragma("GCC diagnostic ignored \"-Wall\"") \
_Pragma("GCC diagnostic ignored \"-Wextra\"")

#define GO_BOOST_END_SUPPRESS_ALL_WARNINGS \
_Pragma("GCC diagnostic pop")

#define GO_BOOST_CLANG_BEGIN_SUPPRESS_WARNING(_warning_) \
_Pragma("GCC diagnostic push") \
GO_BOOST_DO_PRAGMA_EX(GCC diagnostic ignored BOOST_PP_STRINGIZE(BOOST_PP_CAT(-W, _warning_)))

#define GO_BOOST_CLANG_SUPPRESS_WARNING(_warning_) \
GO_BOOST_DO_PRAGMA_EX(GCC diagnostic ignored BOOST_PP_STRINGIZE(BOOST_PP_CAT(-W, _warning_)))

#define GO_BOOST_CLANG_END_SUPPRESS_WARNING \
_Pragma("GCC diagnostic pop")

#else

#define GO_BOOST_BEGIN_SUPPRESS_ALL_WARNINGS
#define GO_BOOST_END_SUPPRESS_ALL_WARNINGS

#define GO_BOOST_CLANG_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_CLANG_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_CLANG_END_SUPPRESS_WARNING

#endif  // #if defined (GO_BOOST_ENABLE_SUPPRESS_WARNINGS)

#define GO_BOOST_GCC_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_GCC_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_GCC_END_SUPPRESS_WARNING

#define GO_BOOST_MSVC_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_MSVC_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_MSVC_END_SUPPRESS_WARNING

#endif  // #if defined(__clang__)

#endif  // #ifndef GO_BOOST_CONFIG_COMPILER_CLANG_HPP_INCLUDED
