#ifndef GO_BOOST_CONFIG_COMPILER_VISUALC_HPP_INCLUDED
#define GO_BOOST_CONFIG_COMPILER_VISUALC_HPP_INCLUDED

//
//  visualc.hpp
//
//  Copyright 2016-2019 Göran Orsander
//
//  This file is part of the GO.libraries.
//  Distributed under the GO Software License, Version 2.0.
//  See accompanying file LICENSE.md.
//

#include <go_boost/config.hpp>

#ifdef BOOST_HAS_PRAGMA_ONCE
#pragma once
#endif  // #ifdef BOOST_HAS_PRAGMA_ONCE

#if defined(BOOST_MSVC)

#define GO_BOOST_COMP_MSVC 1

#define GO_BOOST_MSVC_VER _MSC_VER

#if _MSC_FULL_VER > 100000000
#define GO_BOOST_MSVC_FULL_VER _MSC_FULL_VER
#else
#define GO_BOOST_MSVC_FULL_VER (_MSC_FULL_VER * 10)
#endif  // #if _MSC_FULL_VER > 100000000

#if (_MSC_VER == 800)
#define GO_BOOST_COMP_MSVC_VC10 1
#elif (_MSC_VER == 900)
#define GO_BOOST_COMP_MSVC_VC20 1
#elif (_MSC_VER == 1000)
#define GO_BOOST_COMP_MSVC_VC40 1
#define GO_BOOST_IDE_MS_DS40 1
#elif (_MSC_VER == 1020)
#define GO_BOOST_COMP_MSVC_VC42 1
#define GO_BOOST_IDE_MS_DS42 1
#elif (_MSC_VER == 1100)
#define GO_BOOST_COMP_MSVC_VC50 1
#define GO_BOOST_IDE_MS_VS97 1
#elif (_MSC_VER == 1200)
#define GO_BOOST_COMP_MSVC_VC60 1
#define GO_BOOST_IDE_MS_VS60 1
#elif (_MSC_VER == 1300)
#define GO_BOOST_COMP_MSVC_VC70 1
#define GO_BOOST_IDE_MS_VS2002 1
#elif (_MSC_VER == 1310)
#define GO_BOOST_COMP_MSVC_VC71 1
#define GO_BOOST_IDE_MS_VS2003 1
#elif (_MSC_VER == 1400)
#define GO_BOOST_COMP_MSVC_VC80 1
#define GO_BOOST_IDE_MS_VS2005 1
#elif (_MSC_VER == 1500)
#define GO_BOOST_COMP_MSVC_VC90 1
#define GO_BOOST_IDE_MS_VS2008 1
#elif (_MSC_VER == 1600)
#define GO_BOOST_COMP_MSVC_VC100 1
#define GO_BOOST_IDE_MS_VS2010 1
#elif (_MSC_VER == 1700)
#define GO_BOOST_COMP_MSVC_VC110 1
#define GO_BOOST_IDE_MS_VS2012 1
#elif (_MSC_VER == 1800)
#define GO_BOOST_COMP_MSVC_VC120 1
#define GO_BOOST_IDE_MS_VS2013 1
#elif (_MSC_VER == 1900)
#define GO_BOOST_COMP_MSVC_VC140 1
#define GO_BOOST_IDE_MS_VS2015 1
#elif (_MSC_VER >= 1910) && (_MSC_VER < 1920)
#define GO_BOOST_COMP_MSVC_VC141 1
#define GO_BOOST_IDE_MS_VS2017 1
#if (_MSC_VER == 1910)
#define GO_BOOST_IDE_MS_VS2017_15_0 1
#elif (_MSC_VER == 1911)
#define GO_BOOST_IDE_MS_VS2017_15_3 1
#elif (_MSC_VER == 1912)
#define GO_BOOST_IDE_MS_VS2017_15_5 1
#elif (_MSC_VER == 1913)
#define GO_BOOST_IDE_MS_VS2017_15_6 1
#elif (_MSC_VER == 1914)
#define GO_BOOST_IDE_MS_VS2017_15_7 1
#elif (_MSC_VER == 1915)
#define GO_BOOST_IDE_MS_VS2017_15_8 1
#elif (_MSC_VER == 1916)
#define GO_BOOST_IDE_MS_VS2017_15_9 1
#endif  // #if (_MSC_VER == 1910)
#elif (_MSC_VER >= 1920)
#define GO_BOOST_COMP_MSVC_VC142 1
#define GO_BOOST_IDE_MS_VS2019 1
#if (_MSC_VER == 1920)
#define GO_BOOST_IDE_MS_VS2019_16_0 1
#elif (_MSC_VER == 1921)
#define GO_BOOST_IDE_MS_VS2019_16_1 1
#endif  // #if (_MSC_VER == 1920)
#endif  // #if (_MSC_VER == 800)

// Compiler message
#define GO_BOOST_MESSAGE(_message_) \
__pragma(message(_message_))

// C++ keyword typename support
#if (_MSC_VER < 1900)
#define GO_BOOST_TYPENAME
#else
#define GO_BOOST_TYPENAME typename
#define GO_BOOST_CPP_TYPENAME_REQUIRED 1
#endif  // #if (_MSC_VER < 1900)

// C++ issue workarounds
#if (_MSC_VER < 1900)
#define GO_BOOST_FACET_IS_NOT_A_MEMBER_OF_STD_CODECVT_ISSUE 1
#define GO_BOOST_CANNOT_CREATE_U2STRING_ISSUE 1
#endif  // #if (_MSC_VER < 1900)
#if (_MSC_VER < 1800)
#define GO_BOOST_STD_MUTEX_ASSIGNMENT_OPERATOR_IS_PRIVATE_ISSUE 1
#endif  // #if (_MSC_VER < 1800)

// C++11 support
#if (_MSC_VER < 1900)
#define GO_BOOST_NO_CXX11_ALIGNAS 1
#define GO_BOOST_NO_CXX11_ALIGNOF 1
#define GO_BOOST_NO_CXX11_CONDITION_VARIABLE 1
#define GO_BOOST_NO_CXX11_CONSTEXPR 1
#define GO_BOOST_NO_CXX11_INHERITING_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX11_INLINE_NAMESPACES 1
#define GO_BOOST_NO_CXX11_NEW_CHARACTER_TYPES 1
#define GO_BOOST_NO_CXX11_UNICODE_STRING_LITERALS 1
#define GO_BOOST_NO_CXX11_USER_DEFINED_LITERALS 1
#define GO_BOOST_NO_CXX11_THREAD_LOCAL_STORAGE 1
#define GO_BOOST_NO_CXX11_UNRESTRICTED_UNIONS 1
#define GO_BOOST_NO_CXX11_ATTRIBUTES 1
#define GO_BOOST_NO_CXX11_REF_QUALIFIERS 1
#define GO_BOOST_NO_CXX11_MAGIC_STATICS 1
#define GO_BOOST_NO_CXX11_NOEXCEPT 1
#define GO_BOOST_NO_CXX11_MONEY_TIME_AND_HEXFLOAT_IO_MANIPULATORS 1
#define GO_BOOST_NO_CXX11_INITIALIZER_LISTS 1
#define GO_BOOST_NO_CXX11_NON_STATIC_DATA_MEMBER_INITIALIZERS 1
#define GO_BOOST_NO_CXX11_FIXED_WIDTH_INTEGER_TYPES 1
#define GO_BOOST_NO_CXX11_SNPRINTF 1
#endif  // #if (_MSC_VER < 1900)
#if (_MSC_VER < 1800)
#define GO_BOOST_NO_CXX11_DEFAULTED_AND_DELETED_FUNCTIONS 1
#define GO_BOOST_NO_CXX11_DELEGATING_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX11_EXPLICIT_CONVERSION_OPERATORS 1
#define GO_BOOST_NO_CXX11_EXTENDED_FRIEND_DECLARATIONS 1
#define GO_BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS 1
#define GO_BOOST_NO_CXX11_RAW_STRING_LITERALS 1
#define GO_BOOST_NO_CXX11_TEMPLATE_ALIASES 1
#define GO_BOOST_NO_CXX11_TYPE_ALIASES 1
#define GO_BOOST_NO_CXX11_VARIADIC_TEMPLATES 1
#endif  // #if (_MSC_VER < 1800)
#if (_MSC_VER < 1700)
#define GO_BOOST_NO_CXX11_ATOMIC_OPERATIONS 1
#define GO_BOOST_NO_CXX11_FORWARD_ENUM_DECLARATIONS 1
#define GO_BOOST_NO_CXX11_STRONGLY_TYPED_ENUM 1
#define GO_BOOST_NO_CXX11_RANGE_FOR_LOOP 1
#define GO_BOOST_NO_CXX11_OVERRIDE_AND_FINAL 1
#define GO_BOOST_NO_CXX11_CONCURRENCY_SUPPORT 1
#define GO_BOOST_NO_CXX11_MUTEX 1
#endif  // #if (_MSC_VER < 1700)
#if (_MSC_VER < 1600)
#define GO_BOOST_NO_CXX11_AUTO 1
#define GO_BOOST_NO_CXX11_DECLTYPE 1
#define GO_BOOST_NO_CXX11_LAMBDA_EXPRESSIONS 1
#define GO_BOOST_NO_CXX11_LOCAL_AND_UNNAMED_TYPES_AS_TEMPLATE_PARAMETERS 1
#define GO_BOOST_NO_CXX11_LONG_LONG 1
#define GO_BOOST_NO_CXX11_TRAILING_FUNCTION_RETURN_TYPES 1
#define GO_BOOST_NO_CXX11_NULLPTR 1
#define GO_BOOST_NO_CXX11_R_VALUE_REFERENCES 1
#define GO_BOOST_NO_CXX11_STATIC_ASSERT 1
#define GO_BOOST_NO_CXX11_CHAR16_T 1
#define GO_BOOST_NO_CXX11_CHAR32_T 1
#define GO_BOOST_NO_CXX11_CODECVT 1
#endif  // #if (_MSC_VER < 1600)
#if (_MSC_VER < 1400)
#define GO_BOOST_NO_CXX11_RIGHT_ANGLE_BRACKETS 1
#define GO_BOOST_NO_CXX11_TYPE_TRAITS 1
#endif  // #if (_MSC_VER < 1400)
#if (_MSC_VER < 1200)
#define GO_BOOST_NO_CXX11_EXTERN_TEMPLATE 1
#define GO_BOOST_NO_CXX11 1
#endif  // #if (_MSC_VER < 1200)
#if defined(_MSC_VER)
#define GO_BOOST_NO_CXX11_DYNAMIC_POINTER_SAFETY 1
#endif  // #if defined(_MSC_VER)

#if defined(BOOST_NO_CXX11_CONSTEXPR)
#define GO_BOOST_CONSTEXPR
#else
#define GO_BOOST_CONSTEXPR constexpr
#endif  // #if defined(BOOST_NO_CXX11_CONSTEXPR)

#if defined(BOOST_NO_CXX11_DEFAULTED_FUNCTIONS) || defined(GO_BOOST_COMP_MSVC_VC120)
#define GO_BOOST_DEFAULT_CONSTRUCTOR {}
#define GO_BOOST_DEFAULT_DESTRUCTOR {}
#else
#define GO_BOOST_DEFAULT_CONSTRUCTOR = default;
#define GO_BOOST_DEFAULT_DESTRUCTOR = default;
#endif  // #if defined(BOOST_NO_CXX11_DEFAULTED_FUNCTIONS)

#if defined(GO_BOOST_NO_CXX11_NOEXCEPT)
#define GO_BOOST_NOEXCEPT
#define GO_BOOST_NOEXCEPT_OR_NOTHROW throw()
#define GO_BOOST_NOEXCEPT_IF(_predicate_)
#define GO_BOOST_NOEXCEPT_EXPR(_expression_) false
#else
#define GO_BOOST_NOEXCEPT noexcept
#define GO_BOOST_NOEXCEPT_OR_NOTHROW noexcept
#define GO_BOOST_NOEXCEPT_IF(_predicate_) noexcept((_predicate_))
#define GO_BOOST_NOEXCEPT_EXPR(_expression_) noexcept((_expression_))
#endif  // #if defined(GO_BOOST_NO_CXX11_NOEXCEPT)

#if defined(BOOST_NO_CXX11_NULLPTR)
#define GO_BOOST_NULLPTR NULL
#else
#define GO_BOOST_NULLPTR nullptr
#endif  // #if defined(BOOST_NO_CXX11_NULLPTR)

#if (_MSC_VER < 1700)
#define GO_BOOST_FINAL
#define GO_BOOST_OVERRIDE
#else
#define GO_BOOST_FINAL final
#define GO_BOOST_OVERRIDE override
#endif  // #if (_MSC_VER < 1900)

#if defined(GO_BOOST_NO_CXX11_TEMPLATE_ALIASES)
#define GO_BOOST_USING(_alias_, _type_) typedef _type_ _alias_
#else
#define GO_BOOST_USING(_alias_, _type_) using _alias_ = _type_;
#endif  // #if defined(GO_BOOST_NO_CXX11_TEMPLATE_ALIASES)

// C++14 support
#if (_MSC_VER < 1910)
#define GO_BOOST_NO_CXX14_EXTENDED_CONSTEXPR 1
#define GO_BOOST_NO_CXX14_MEMBER_INITIALIZERS_AND_AGGREGATES 1
#endif  // #if (_MSC_VER < 1910)
#if (_MSC_VER < 1900)
#define GO_BOOST_NO_CXX14_BINARY_LITERALS 1
#define GO_BOOST_NO_CXX14_DECLTYPE_AUTO 1
#define GO_BOOST_NO_CXX14_INITIALIZED_GENERALIZED_LAMBDA_CAPTURES 1
#define GO_BOOST_NO_CXX14_GENERIC_POLYMORPHIC_LAMBDA_EXPRESSIONS 1
#define GO_BOOST_NO_CXX14_VARIABLE_TEMPLATES 1
#define GO_BOOST_NO_CXX14_DEPRECATED_ATTRIBUTE 1
#define GO_BOOST_NO_CXX14_SIZED_DEALLOCATION 1
#define GO_BOOST_NO_CXX14_SINGLE_QUOTE_AS_DIGIT_SEPARATOR 1
#define GO_BOOST_NO_CXX14_STD_RESULT_OF_AND_SFINAE 1
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_COMPLEX 1
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_CHRONO 1
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_ARRAY 1
#define GO_BOOST_NO_CXX14_CONSTEXPR_FOR_INITIALIZER_LIST_UTILITY_AND_TUPLE 1
#define GO_BOOST_NO_CXX14_IMPROVED_STD_INTEGRAL_CONSTANT 1
#define GO_BOOST_NO_CXX14_USER_DEFINED_LITERALS_FOR_CHRONO_AND_STRING 1
#define GO_BOOST_NO_CXX14_NULL_FORWARD_ITERATORS 1
#define GO_BOOST_NO_CXX14_STD_QUOTED 1
#define GO_BOOST_NO_CXX14_HETEROGENEOUS_ASSOCIATIVE_LOOKUP 1
#define GO_BOOST_NO_CXX14_STD_INTEGER_SEQUENCE 1
#define GO_BOOST_NO_CXX14_STD_SHARED_TIMED_MUTEX 1
#define GO_BOOST_NO_CXX14_STD_EXCHANGE 1
#define GO_BOOST_NO_CXX14_FIXING_CONSTEXPR_MEMBER_FUNCTIONS_WITHOUT_CONST 1
#define GO_BOOST_NO_CXX14_STD_GET_T 1
#define GO_BOOST_NO_CXX14_DUAL_RANGE_STD_EQUAL_STD_IS_PERMUTATION_STD_MISMATCH 1
#endif  // #if (_MSC_VER < 1900)
#if (_MSC_VER < 1800)
#define GO_BOOST_NO_CXX14_TWEAKED_WORDING_FOR_CONTEXTUAL_CONVERSIONS 1
#define GO_BOOST_NO_CXX14 1
#endif  // #if (_MSC_VER < 1800)
#if defined(_MSC_VER)
#define GO_BOOST_NO_CXX14_CLARIFYING_MEMORY_ALLOCATION 1
#define GO_BOOST_NO_CXX14_LAMBDA_DEFAULT_ARGUMENTS 1
#endif  // #if defined(_MSC_VER)

// C++17 support
#if (_MSC_VER < 1915)
#define GO_BOOST_NO_CXX17_ELEMENTARY_STRING_CONVERSIONS 1
#endif  // #if (_MSC_VER < 1915)
#if (_MSC_VER < 1914)
#define GO_BOOST_NO_CXX17_AGGREGATE_INITIALIZATION_OF_CLASSES_WITH_BASE_CLASSES 1
#define GO_BOOST_NO_CXX17_TEMPLATE_ARGUMENT_DEDUCTION_FOR_CLASS_TEMPLATES 1
#define GO_BOOST_NO_CXX17_NONTYPE_TEMPLATE_PARAMETERS_WITH_AUTO_TYPE 1
#define GO_BOOST_NO_CXX17_NEW_SPECIFICATION_FOR_INHERITING_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX17_REPLACEMENT_OF_CLASS_OBJECTS_CONTAINING_REFERENCE_MEMBERS 1
#define GO_BOOST_NO_CXX17_STRICTER_EXPRESSION_EVALUATION_ORDER 1
#define GO_BOOST_NO_CXX17_PACK_EXPANSIONS_IN_USING_DECLARATIONS 1
#define GO_BOOST_NO_CXX17_STANDARDIZATION_OF_PARALLELISM_TS 1
#define GO_BOOST_NO_CXX17_MATHEMATICAL_SPECIAL_FUNCTIONS 1
#define GO_BOOST_NO_CXX17_STD_FILESYSTEM 1
#endif  // #if (_MSC_VER < 1914)
#if (_MSC_VER < 1913)
#define GO_BOOST_NO_CXX17_GUARANTEED_COPY_ELISION 1
#endif  // #if (_MSC_VER < 1913)
#if (_MSC_VER < 1912)
#define GO_BOOST_NO_CXX17_ALLOW_CONSTANT_EVALUATION_FOR_ALL_NONTYPE_TEMPLATE_ARGUMENTS 1
#define GO_BOOST_NO_CXX17_FOLD_EXPRESSIONS 1
#define GO_BOOST_NO_CXX17_MAKE_EXCEPTION_SPECIFICATIONS_PART_OF_THE_TYPE_SYSTEM 1
#define GO_BOOST_NO_CXX17_DYNAMIC_MEMORY_ALLOCATION_FOR_OVERALIGNED_DATA 1
#define GO_BOOST_NO_CXX17_UNARY_FOLD_EXPRESSIONS_AND_EMPTY_PARAMETER_PACKS 1
#define GO_BOOST_NO_CXX17_INLINE_VARIABLES 1
#define GO_BOOST_NO_CXX17_MATCHING_OF_TEMPLATE_TEMPLATE_ARGUMENTS_EXCLUDES_COMPATIBLE_TEMPLATES 1
#define GO_BOOST_NO_CXX17_SPLICING_MAPS_AND_SETS 1
#endif  // #if (_MSC_VER < 1912)
#if (_MSC_VER < 1911)
#define GO_BOOST_NO_CXX17_REMOVE_DEPRECATED_USE_OF_THE_REGISTER_KEYWORD 1
#define GO_BOOST_NO_CXX17_REMOVE_DEPRECATED_OPERATOR_PLUSPLUS_BOOL 1
#define GO_BOOST_NO_CXX17_LAMBDA_CAPTURE_OF_INDIRECTED_THIS 1
#define GO_BOOST_NO_CXX17_USING_ATTRIBUTE_NAMESPACES_WITHOUT_REPETITION 1
#define GO_BOOST_NO_CXX17_HAS_INCLUDE_IN_PREPROCESSOR_CONDITIONALS 1
#define GO_BOOST_NO_CXX17_DIRECT_LIST_INITIALIZATION_OF_ENUMERATIONS 1
#define GO_BOOST_NO_CXX17_CONSTEXPR_LAMBDA_EXPRESSIONS 1
#define GO_BOOST_NO_CXX17_NODISCARD_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_MAYBE_UNUSED_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_STRUCTURED_BINDINGS 1
#define GO_BOOST_NO_CXX17_HEXADECIMAL_FLOATING_POINT_LITERALS 1
#define GO_BOOST_NO_CXX17_IGNORE_UNKNOWN_ATTRIBUTES 1
#define GO_BOOST_NO_CXX17_CONSTEXPR_IF_STATEMENTS 1
#define GO_BOOST_NO_CXX17_INIT_STATEMENTS_FOR_IF_AND_SWITCH 1
#define GO_BOOST_NO_CXX17_STD_BYTE 1
#endif  // #if (_MSC_VER < 1911)
#if (_MSC_VER < 1910)
#define GO_BOOST_NO_CXX17_STATIC_ASSERT_WITH_NO_MESSAGE 1
#define GO_BOOST_NO_CXX17_REMOVING_DEPRECATED_EXCEPTION_SPECIFICATIONS 1
#define GO_BOOST_NO_CXX17_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR 1
#define GO_BOOST_NO_CXX17_FALLTHROUGH_ATTRIBUTE 1
#define GO_BOOST_NO_CXX17_STD_ANY 1
#define GO_BOOST_NO_CXX17_STD_VARIANT 1
#define GO_BOOST_NO_CXX17_STD_OPTIONAL 1
#define GO_BOOST_NO_CXX17_STD_STRING_VIEW 1
#define GO_BOOST_NO_CXX17_HARDWARE_INTERFERENCE_SIZE 1
#endif  // #if (_MSC_VER < 1910)
#if (_MSC_VER < 1900)
#define GO_BOOST_NO_CXX17_NEW_AUTO_RULES_FOR_DIRECT_LIST_INITIALIZATION 1
#define GO_BOOST_NO_CXX17_TYPENAME_IN_A_TEMPLATE_TEMPLATE_PARAMETER 1
#define GO_BOOST_NO_CXX17_NESTED_NAMESPACE_DEFINITION 1
#define GO_BOOST_NO_CXX17_ATTRIBUTES_FOR_NAMESPACES_AND_ENUMERATORS 1
#define GO_BOOST_NO_CXX17_U8_CHARACTER_LITERALS 1
#define GO_BOOST_NO_CXX17_STD_UNCAUGHT_EXCEPTIONS 1
#define GO_BOOST_NO_CXX17_IMPROVING_STD_PAIR_AND_STD_TUPLE 1
#define GO_BOOST_NO_CXX17_STD_SHARED_MUTEX_UNTIMED 1
#endif  // #if (_MSC_VER < 1900)
#if (_MSC_VER < 1600)
#define GO_BOOST_NO_CXX17_REMOVING_TRIGRAPHS 1
#define GO_BOOST_NO_CXX17 1
#endif  // #if (_MSC_VER < 1600)

// C++2a support
#if (_MSC_VER < 1915)
#define GO_BOOST_NO_CXX2A_INTEGRATING_OUR_FEATURE_TEST_MACROS 1
#define GO_BOOST_NO_CXX2A 1
#endif  // #if (_MSC_VER < 1915)
#if defined(_MSC_VER)
#define GO_BOOST_NO_CXX2A_CONCEPTS 1
#define GO_BOOST_NO_CXX2A_CONTRACTS 1
#define GO_BOOST_NO_CXX2A_DEFAULT_MEMBER_INITIALIZERS_FOR_BIT_FIELDS 1
#define GO_BOOST_NO_CXX2A_CONST_REF_QUALIFIED_POINTERS_TO_MEMBERS 1
#define GO_BOOST_NO_CXX2A_ALLOW_LAMBDA_CAPTURE_ASSIGN_THIS 1
#define GO_BOOST_NO_CXX2A_VA_OPT 1
#define GO_BOOST_NO_CXX2A_DESIGNATED_INITIALIZERS 1
#define GO_BOOST_NO_CXX2A_TEMPLATE_PARAMETER_LIST_FOR_GENERIC_LAMBDAS 1
#define GO_BOOST_NO_CXX2A_SIMPLIFYING_IMPLICIT_LAMBDA_CAPTURE 1
#define GO_BOOST_NO_CXX2A_ADL_AND_FUNCTION_TEMPLATES_THAT_ARE_NOT_VISIBLE 1
#define GO_BOOST_NO_CXX2A_CONST_MISMATCH_WITH_DEFAULTED_COPY_CONSTRUCTOR 1
#define GO_BOOST_NO_CXX2A_INITIALIZER_LIST_CONSTRUCTORS_IN_CLASS_TEMPLATE_ARGUMENT_DEDUCTION 1
#define GO_BOOST_NO_CXX2A_INIT_STATEMENTS_FOR_RANGE_BASED_FOR 1
#define GO_BOOST_NO_CXX2A_THREE_WAY_COMPARISON_OPERATOR 1
#define GO_BOOST_NO_CXX2A_ATTRIBUTE_NO_UNIQUE_ADDRESS 1
#define GO_BOOST_NO_CXX2A_ATTRIBUTES_LIKELY_AND_UNLIKELY 1
#define GO_BOOST_NO_CXX2A_TYPENAME_OPTIONAL 1
#define GO_BOOST_NO_CXX2A_LESS_EAGER_INSTANTIATION_OF_CONSTEXPR_FUNCTIONS 1
#define GO_BOOST_NO_CXX2A_CLASS_TYPES_IN_NON_TYPE_TEMPLATE_PARAMETERS 1
#define GO_BOOST_NO_CXX2A_EXPLICIT_BOOL 1
#define GO_BOOST_NO_CXX2A_CONSTEXPR_VIRTUAL_FUNCTION 1
#define GO_BOOST_NO_CXX2A_PROHIBIT_AGGREGATES_WITH_USER_DECLARED_CONSTRUCTORS 1
#define GO_BOOST_NO_CXX2A_EFFICIENT_SIZED_DELETE_FOR_VARIABLE_SIZED_CLASSES 1
#define GO_BOOST_NO_CXX2A_ACCESS_CHECKING_ON_SPECIALIZATIONS 1
#define GO_BOOST_NO_CXX2A_PACK_EXPANSION_IN_LAMBDA_INIT_CAPTURE 1
#define GO_BOOST_NO_CXX2A_DEFAULT_CONSTRUCTIBLE_AND_ASSIGNABLE_STATELESS_LAMBDAS 1
#define GO_BOOST_NO_CXX2A_LAMBDAS_IN_UNEVALUATED_CONTEXTS 1
#define GO_BOOST_NO_CXX2A_CONCEPTS_LIBRARY 1
#define GO_BOOST_NO_CXX2A_THREE_WAY_COMPARISON_OPERATOR_SUPPORT_COMPARE 1
#define GO_BOOST_NO_CXX2A_STD_ENDIAN 1
#define GO_BOOST_NO_CXX2A_STD_ATOMIC_REF 1
#define GO_BOOST_NO_CXX2A_STD_BIT_CAST 1
#define GO_BOOST_NO_CXX2A_EXTENDING_STD_MAKE_SHARED_TO_SUPPORT_ARRAYS 1
#define GO_BOOST_NO_CXX2A_CALENDAR_AND_TIMEZONE 1
#define GO_BOOST_NO_CXX2A_STD_SPAN 1
#define GO_BOOST_NO_CXX2A_FLOATING_POINT_ATOMIC 1
#define GO_BOOST_NO_CXX2A_SYNCHRONIZED_BUFFERED_OSTREAM 1
#define GO_BOOST_NO_CXX2A_CONSTEXPR_FOR_ALGORITHM_AND_UTILITY 1
#define GO_BOOST_NO_CXX2A_MORE_CONSTEXPR_FOR_COMPLEX 1
#define GO_BOOST_NO_CXX2A_STD_REMOVE_CVREF 1
#define GO_BOOST_NO_CXX2A_STRING_PREFIX_AND_SUFFIX_CHECKING 1
#define GO_BOOST_NO_CXX2A_UTILITY_TO_CONVERT_A_POINTER_TO_A_RAW_POINTER 1
#define GO_BOOST_NO_CXX2A_VERSION 1
#endif  // #if defined(_MSC_VER)

// C99 support
#if defined(_MSC_VER)
#define GO_BOOST_NO_C99_PREPROCESSOR 1
#endif  // #if defined(_MSC_VER)

// ATL support
#if defined(_ATL_VER)
#define GO_BOOST_MSVC_ATL 1
#define GO_BOOST_MSVC_ATL_VER _MFX_VER
#endif  // if defined(_ATL_VER)

// MFC support
#if defined(_MFC_VER)
#define GO_BOOST_MSVC_MFC 1
#define GO_BOOST_MSVC_MFC_VER _MFX_VER
#endif  // if defined(_MFC_VER)

// Unicode support
#if defined(_UNICODE) || defined(UNICODE)
#define GO_BOOST_MSVC_UNICODE 1
#endif  // if defined(_UNICODE) || defined(UNICODE)

// Boost libraries support
#if (_MSC_VER < 1800)
#define GO_BOOST_NO_BOOST_PHOENIX 1
#endif  // #if (_MSC_VER < 1900)

// Treat some warnings as error
#pragma warning (error: 4355) // 'this' : used in base member initializer list

// Suppress warnings
#if defined (GO_BOOST_ENABLE_SUPPRESS_WARNINGS)

#define GO_BOOST_BEGIN_SUPPRESS_ALL_WARNINGS \
__pragma(warning(push, 0))

#define GO_BOOST_END_SUPPRESS_ALL_WARNINGS \
__pragma(warning(pop))

#define GO_BOOST_MSVC_BEGIN_SUPPRESS_WARNING(_warning_) \
__pragma(warning(push)) \
__pragma(warning(disable: _warning_))

#define GO_BOOST_MSVC_SUPPRESS_WARNING(_warning_) \
__pragma(warning(disable: _warning_))

#define GO_BOOST_MSVC_END_SUPPRESS_WARNING \
__pragma(warning(pop))

#else

#define GO_BOOST_BEGIN_SUPPRESS_ALL_WARNINGS
#define GO_BOOST_END_SUPPRESS_ALL_WARNINGS

#define GO_BOOST_MSVC_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_MSVC_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_MSVC_END_SUPPRESS_WARNING

#endif  // #if defined (GO_BOOST_ENABLE_SUPPRESS_WARNINGS)

#define GO_BOOST_CLANG_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_CLANG_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_CLANG_END_SUPPRESS_WARNING

#define GO_BOOST_GCC_BEGIN_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_GCC_SUPPRESS_WARNING(_warning_)
#define GO_BOOST_GCC_END_SUPPRESS_WARNING

#endif  // #if defined(BOOST_MSVC)

#endif  // #ifndef GO_BOOST_CONFIG_COMPILER_VISUALC_HPP_INCLUDED
